/**
 * Autogenerated file. Please don't touch if you don't know :)
 * Class generator: ink.reactor.dataparser.type.dimension.DimensionDataParser (module data-parser)
 * Date: Year: 2025. Month: 03. Day: 31. Hour: 01:44:40 (24h format)
 * <p>
 * Jsons combined using
 *   @see ink.reactor.dataparser.util.JsonCombiner
 * .json files generated with Data generators.
 *   <a href="https://minecraft.wiki/w/Minecraft_Wiki:Projects/wiki.vg_merge/Data_Generators">Data generators</a>
 */
package ink.reactor.world.data;

import java.util.List;
import java.util.ArrayList;

public record DimensionType(
    String name,
    String infiniburn,
    String effects,
    long fixedTime,
    boolean hasSkyLight,
    boolean hasCeiling,
    boolean ultrawarm,
    boolean natural,
    boolean bedWorks,
    boolean respawnAnchorWorks,
    boolean piglinSafe,
    boolean hasRaids,
    int id,
    int minY,
    int height,
    int localHeight,
    int monsterSpawnLightLevel,
    int monsterSpawnBlockLightLimit,
    double coordinateScale,
    double ambientLight
) {
    public static final List<DimensionType> ALL = new ArrayList<>(4);
    public static final DimensionType OVERWORLD = vanilla("overworld","#minecraft:infiniburn_overworld","minecraft:overworld",0,true,false,false,true,true,false,false,true,0,-64,384,384,0,0,1.0,0.0);
    public static final DimensionType OVERWORLD_CAVES = vanilla("overworld_caves","#minecraft:infiniburn_overworld","minecraft:overworld",0,true,true,false,true,true,false,false,true,1,-64,384,384,0,0,1.0,0.0);
    public static final DimensionType THE_END = vanilla("the_end","#minecraft:infiniburn_end","minecraft:the_end",6000,false,false,false,false,false,false,false,true,2,0,256,256,0,0,1.0,0.0);
    public static final DimensionType THE_NETHER = vanilla("the_nether","#minecraft:infiniburn_nether","minecraft:the_nether",18000,false,true,true,false,false,true,true,false,3,0,256,128,15,7,8.0,0.1);
    private static DimensionType vanilla(String name, String infiniburn, String effects, long fixedTime, boolean hasSkyLight, boolean hasCeiling, boolean ultrawarm, boolean natural, boolean bedWorks, boolean respawnAnchorWorks, boolean piglinSafe, boolean hasRaids, int id, int minY, int height, int localHeight, int monsterSpawnLightLevel, int monsterSpawnBlockLightLimit, double coordinateScale, double ambientLight) {
        final DimensionType instance = new DimensionType(name, infiniburn, effects, fixedTime, hasSkyLight, hasCeiling, ultrawarm, natural, bedWorks, respawnAnchorWorks, piglinSafe, hasRaids, id, minY, height, localHeight, monsterSpawnLightLevel, monsterSpawnBlockLightLimit, coordinateScale, ambientLight);
        ALL.add(instance);
        return instance;
    }

    public int hashCode() {
        return id;
    }
}