/*
* Autogenerated file. Please don't touch :)
* Class generator: ink.reactor.dataparser.other.effect.EffectParser (module data-parser)
* Date: Year: 2025. Month: 02. Day: 20. Time: 22:26:31
*/
package ink.reactor.entity.effect;

public enum EffectType {
    SPEED,
    SLOWNESS,
    HASTE,
    MINING_FATIGUE,
    STRENGTH,
    INSTANT_HEALTH,
    INSTANT_DAMAGE,
    JUMP_BOOST,
    NAUSEA,
    REGENERATION,
    RESISTANCE,
    FIRE_RESISTANCE,
    WATER_BREATHING,
    INVISIBILITY,
    BLINDNESS,
    NIGHT_VISION,
    HUNGER,
    WEAKNESS,
    POISON,
    WITHER,
    HEALTH_BOOST,
    ABSORPTION,
    SATURATION,
    GLOWING,
    LEVITATION,
    LUCK,
    BAD_LUCK,
    SLOW_FALLING,
    CONDUIT_POWER,
    DOLPHINS_GRACE,
    BAD_OMEN,
    HERO_OF_THE_VILLAGE,
    DARKNESS,
    TRIAL_OMEN,
    RAID_OMEN,
    WIND_CHARGED,
    WEAVING,
    OOZING,
    INFESTED;
}