package ink.reactor.world.block.state;

public final class ChorusPlant {
    public static int of(final char id, final boolean down, final boolean east, final boolean north, final boolean south, final boolean up, final boolean west) {
        final String sentence = down+"-"+east+"-"+north+"-"+south+"-"+up+"-"+west;
        return switch(sentence) {
            case "true-true-true-true-true-true" -> id-63;
            case "true-true-true-true-true-false" -> id-62;
            case "true-true-true-true-false-true" -> id-61;
            case "true-true-true-true-false-false" -> id-60;
            case "true-true-true-false-true-true" -> id-59;
            case "true-true-true-false-true-false" -> id-58;
            case "true-true-true-false-false-true" -> id-57;
            case "true-true-true-false-false-false" -> id-56;
            case "true-true-false-true-true-true" -> id-55;
            case "true-true-false-true-true-false" -> id-54;
            case "true-true-false-true-false-true" -> id-53;
            case "true-true-false-true-false-false" -> id-52;
            case "true-true-false-false-true-true" -> id-51;
            case "true-true-false-false-true-false" -> id-50;
            case "true-true-false-false-false-true" -> id-49;
            case "true-true-false-false-false-false" -> id-48;
            case "true-false-true-true-true-true" -> id-47;
            case "true-false-true-true-true-false" -> id-46;
            case "true-false-true-true-false-true" -> id-45;
            case "true-false-true-true-false-false" -> id-44;
            case "true-false-true-false-true-true" -> id-43;
            case "true-false-true-false-true-false" -> id-42;
            case "true-false-true-false-false-true" -> id-41;
            case "true-false-true-false-false-false" -> id-40;
            case "true-false-false-true-true-true" -> id-39;
            case "true-false-false-true-true-false" -> id-38;
            case "true-false-false-true-false-true" -> id-37;
            case "true-false-false-true-false-false" -> id-36;
            case "true-false-false-false-true-true" -> id-35;
            case "true-false-false-false-true-false" -> id-34;
            case "true-false-false-false-false-true" -> id-33;
            case "true-false-false-false-false-false" -> id-32;
            case "false-true-true-true-true-true" -> id-31;
            case "false-true-true-true-true-false" -> id-30;
            case "false-true-true-true-false-true" -> id-29;
            case "false-true-true-true-false-false" -> id-28;
            case "false-true-true-false-true-true" -> id-27;
            case "false-true-true-false-true-false" -> id-26;
            case "false-true-true-false-false-true" -> id-25;
            case "false-true-true-false-false-false" -> id-24;
            case "false-true-false-true-true-true" -> id-23;
            case "false-true-false-true-true-false" -> id-22;
            case "false-true-false-true-false-true" -> id-21;
            case "false-true-false-true-false-false" -> id-20;
            case "false-true-false-false-true-true" -> id-19;
            case "false-true-false-false-true-false" -> id-18;
            case "false-true-false-false-false-true" -> id-17;
            case "false-true-false-false-false-false" -> id-16;
            case "false-false-true-true-true-true" -> id-15;
            case "false-false-true-true-true-false" -> id-14;
            case "false-false-true-true-false-true" -> id-13;
            case "false-false-true-true-false-false" -> id-12;
            case "false-false-true-false-true-true" -> id-11;
            case "false-false-true-false-true-false" -> id-10;
            case "false-false-true-false-false-true" -> id-9;
            case "false-false-true-false-false-false" -> id-8;
            case "false-false-false-true-true-true" -> id-7;
            case "false-false-false-true-true-false" -> id-6;
            case "false-false-false-true-false-true" -> id-5;
            case "false-false-false-true-false-false" -> id-4;
            case "false-false-false-false-true-true" -> id-3;
            case "false-false-false-false-true-false" -> id-2;
            case "false-false-false-false-false-true" -> id-1;
            default -> id;
        };
    }
}