package ink.reactor.world.block.state;

public final class Repeater {
    public static int of(final char id, final long delay, final BlockFacing facing, final boolean locked, final boolean powered) {
        final String sentence = delay+"-"+facing+"-"+locked+"-"+powered;
        return switch(sentence) {
            case "1-NORTH-true-true" -> id-3;
            case "1-NORTH-true-false" -> id-2;
            case "1-NORTH-false-true" -> id-1;
            case "1-SOUTH-true-true" -> id+1;
            case "1-SOUTH-true-false" -> id+2;
            case "1-SOUTH-false-true" -> id+3;
            case "1-SOUTH-false-false" -> id+4;
            case "1-WEST-true-true" -> id+5;
            case "1-WEST-true-false" -> id+6;
            case "1-WEST-false-true" -> id+7;
            case "1-WEST-false-false" -> id+8;
            case "1-EAST-true-true" -> id+9;
            case "1-EAST-true-false" -> id+10;
            case "1-EAST-false-true" -> id+11;
            case "1-EAST-false-false" -> id+12;
            case "2-NORTH-true-true" -> id+13;
            case "2-NORTH-true-false" -> id+14;
            case "2-NORTH-false-true" -> id+15;
            case "2-NORTH-false-false" -> id+16;
            case "2-SOUTH-true-true" -> id+17;
            case "2-SOUTH-true-false" -> id+18;
            case "2-SOUTH-false-true" -> id+19;
            case "2-SOUTH-false-false" -> id+20;
            case "2-WEST-true-true" -> id+21;
            case "2-WEST-true-false" -> id+22;
            case "2-WEST-false-true" -> id+23;
            case "2-WEST-false-false" -> id+24;
            case "2-EAST-true-true" -> id+25;
            case "2-EAST-true-false" -> id+26;
            case "2-EAST-false-true" -> id+27;
            case "2-EAST-false-false" -> id+28;
            case "3-NORTH-true-true" -> id+29;
            case "3-NORTH-true-false" -> id+30;
            case "3-NORTH-false-true" -> id+31;
            case "3-NORTH-false-false" -> id+32;
            case "3-SOUTH-true-true" -> id+33;
            case "3-SOUTH-true-false" -> id+34;
            case "3-SOUTH-false-true" -> id+35;
            case "3-SOUTH-false-false" -> id+36;
            case "3-WEST-true-true" -> id+37;
            case "3-WEST-true-false" -> id+38;
            case "3-WEST-false-true" -> id+39;
            case "3-WEST-false-false" -> id+40;
            case "3-EAST-true-true" -> id+41;
            case "3-EAST-true-false" -> id+42;
            case "3-EAST-false-true" -> id+43;
            case "3-EAST-false-false" -> id+44;
            case "4-NORTH-true-true" -> id+45;
            case "4-NORTH-true-false" -> id+46;
            case "4-NORTH-false-true" -> id+47;
            case "4-NORTH-false-false" -> id+48;
            case "4-SOUTH-true-true" -> id+49;
            case "4-SOUTH-true-false" -> id+50;
            case "4-SOUTH-false-true" -> id+51;
            case "4-SOUTH-false-false" -> id+52;
            case "4-WEST-true-true" -> id+53;
            case "4-WEST-true-false" -> id+54;
            case "4-WEST-false-true" -> id+55;
            case "4-WEST-false-false" -> id+56;
            case "4-EAST-true-true" -> id+57;
            case "4-EAST-true-false" -> id+58;
            case "4-EAST-false-true" -> id+59;
            case "4-EAST-false-false" -> id+60;
            default -> id;
        };
    }
}