package ink.reactor.world.block.state;

public final class Stair {
    public static int of(final char id, final BlockFacing facing, final BlockHalf half, final BlockShape shape, final boolean waterlogged) {
        final String sentence = facing+"-"+half+"-"+shape+"-"+waterlogged;
        return switch(sentence) {
            case "NORTH-TOP-STRAIGHT-true" -> id-11;
            case "NORTH-TOP-STRAIGHT-false" -> id-10;
            case "NORTH-TOP-INNER_LEFT-true" -> id-9;
            case "NORTH-TOP-INNER_LEFT-false" -> id-8;
            case "NORTH-TOP-INNER_RIGHT-true" -> id-7;
            case "NORTH-TOP-INNER_RIGHT-false" -> id-6;
            case "NORTH-TOP-OUTER_LEFT-true" -> id-5;
            case "NORTH-TOP-OUTER_LEFT-false" -> id-4;
            case "NORTH-TOP-OUTER_RIGHT-true" -> id-3;
            case "NORTH-TOP-OUTER_RIGHT-false" -> id-2;
            case "NORTH-BOTTOM-STRAIGHT-true" -> id-1;
            case "NORTH-BOTTOM-INNER_LEFT-true" -> id+1;
            case "NORTH-BOTTOM-INNER_LEFT-false" -> id+2;
            case "NORTH-BOTTOM-INNER_RIGHT-true" -> id+3;
            case "NORTH-BOTTOM-INNER_RIGHT-false" -> id+4;
            case "NORTH-BOTTOM-OUTER_LEFT-true" -> id+5;
            case "NORTH-BOTTOM-OUTER_LEFT-false" -> id+6;
            case "NORTH-BOTTOM-OUTER_RIGHT-true" -> id+7;
            case "NORTH-BOTTOM-OUTER_RIGHT-false" -> id+8;
            case "SOUTH-TOP-STRAIGHT-true" -> id+9;
            case "SOUTH-TOP-STRAIGHT-false" -> id+10;
            case "SOUTH-TOP-INNER_LEFT-true" -> id+11;
            case "SOUTH-TOP-INNER_LEFT-false" -> id+12;
            case "SOUTH-TOP-INNER_RIGHT-true" -> id+13;
            case "SOUTH-TOP-INNER_RIGHT-false" -> id+14;
            case "SOUTH-TOP-OUTER_LEFT-true" -> id+15;
            case "SOUTH-TOP-OUTER_LEFT-false" -> id+16;
            case "SOUTH-TOP-OUTER_RIGHT-true" -> id+17;
            case "SOUTH-TOP-OUTER_RIGHT-false" -> id+18;
            case "SOUTH-BOTTOM-STRAIGHT-true" -> id+19;
            case "SOUTH-BOTTOM-STRAIGHT-false" -> id+20;
            case "SOUTH-BOTTOM-INNER_LEFT-true" -> id+21;
            case "SOUTH-BOTTOM-INNER_LEFT-false" -> id+22;
            case "SOUTH-BOTTOM-INNER_RIGHT-true" -> id+23;
            case "SOUTH-BOTTOM-INNER_RIGHT-false" -> id+24;
            case "SOUTH-BOTTOM-OUTER_LEFT-true" -> id+25;
            case "SOUTH-BOTTOM-OUTER_LEFT-false" -> id+26;
            case "SOUTH-BOTTOM-OUTER_RIGHT-true" -> id+27;
            case "SOUTH-BOTTOM-OUTER_RIGHT-false" -> id+28;
            case "WEST-TOP-STRAIGHT-true" -> id+29;
            case "WEST-TOP-STRAIGHT-false" -> id+30;
            case "WEST-TOP-INNER_LEFT-true" -> id+31;
            case "WEST-TOP-INNER_LEFT-false" -> id+32;
            case "WEST-TOP-INNER_RIGHT-true" -> id+33;
            case "WEST-TOP-INNER_RIGHT-false" -> id+34;
            case "WEST-TOP-OUTER_LEFT-true" -> id+35;
            case "WEST-TOP-OUTER_LEFT-false" -> id+36;
            case "WEST-TOP-OUTER_RIGHT-true" -> id+37;
            case "WEST-TOP-OUTER_RIGHT-false" -> id+38;
            case "WEST-BOTTOM-STRAIGHT-true" -> id+39;
            case "WEST-BOTTOM-STRAIGHT-false" -> id+40;
            case "WEST-BOTTOM-INNER_LEFT-true" -> id+41;
            case "WEST-BOTTOM-INNER_LEFT-false" -> id+42;
            case "WEST-BOTTOM-INNER_RIGHT-true" -> id+43;
            case "WEST-BOTTOM-INNER_RIGHT-false" -> id+44;
            case "WEST-BOTTOM-OUTER_LEFT-true" -> id+45;
            case "WEST-BOTTOM-OUTER_LEFT-false" -> id+46;
            case "WEST-BOTTOM-OUTER_RIGHT-true" -> id+47;
            case "WEST-BOTTOM-OUTER_RIGHT-false" -> id+48;
            case "EAST-TOP-STRAIGHT-true" -> id+49;
            case "EAST-TOP-STRAIGHT-false" -> id+50;
            case "EAST-TOP-INNER_LEFT-true" -> id+51;
            case "EAST-TOP-INNER_LEFT-false" -> id+52;
            case "EAST-TOP-INNER_RIGHT-true" -> id+53;
            case "EAST-TOP-INNER_RIGHT-false" -> id+54;
            case "EAST-TOP-OUTER_LEFT-true" -> id+55;
            case "EAST-TOP-OUTER_LEFT-false" -> id+56;
            case "EAST-TOP-OUTER_RIGHT-true" -> id+57;
            case "EAST-TOP-OUTER_RIGHT-false" -> id+58;
            case "EAST-BOTTOM-STRAIGHT-true" -> id+59;
            case "EAST-BOTTOM-STRAIGHT-false" -> id+60;
            case "EAST-BOTTOM-INNER_LEFT-true" -> id+61;
            case "EAST-BOTTOM-INNER_LEFT-false" -> id+62;
            case "EAST-BOTTOM-INNER_RIGHT-true" -> id+63;
            case "EAST-BOTTOM-INNER_RIGHT-false" -> id+64;
            case "EAST-BOTTOM-OUTER_LEFT-true" -> id+65;
            case "EAST-BOTTOM-OUTER_LEFT-false" -> id+66;
            case "EAST-BOTTOM-OUTER_RIGHT-true" -> id+67;
            case "EAST-BOTTOM-OUTER_RIGHT-false" -> id+68;
            default -> id;
        };
    }
}