package ink.reactor.world.block.state;

public final class WeatheringCopperDoor {
    public static int of(final char id, final BlockFacing facing, final BlockHalf half, final BlockHinge hinge, final boolean open, final boolean powered) {
        final String sentence = facing+"-"+half+"-"+hinge+"-"+open+"-"+powered;
        return switch(sentence) {
            case "NORTH-UPPER-LEFT-true-true" -> id-11;
            case "NORTH-UPPER-LEFT-true-false" -> id-10;
            case "NORTH-UPPER-LEFT-false-true" -> id-9;
            case "NORTH-UPPER-LEFT-false-false" -> id-8;
            case "NORTH-UPPER-RIGHT-true-true" -> id-7;
            case "NORTH-UPPER-RIGHT-true-false" -> id-6;
            case "NORTH-UPPER-RIGHT-false-true" -> id-5;
            case "NORTH-UPPER-RIGHT-false-false" -> id-4;
            case "NORTH-LOWER-LEFT-true-true" -> id-3;
            case "NORTH-LOWER-LEFT-true-false" -> id-2;
            case "NORTH-LOWER-LEFT-false-true" -> id-1;
            case "NORTH-LOWER-RIGHT-true-true" -> id+1;
            case "NORTH-LOWER-RIGHT-true-false" -> id+2;
            case "NORTH-LOWER-RIGHT-false-true" -> id+3;
            case "NORTH-LOWER-RIGHT-false-false" -> id+4;
            case "SOUTH-UPPER-LEFT-true-true" -> id+5;
            case "SOUTH-UPPER-LEFT-true-false" -> id+6;
            case "SOUTH-UPPER-LEFT-false-true" -> id+7;
            case "SOUTH-UPPER-LEFT-false-false" -> id+8;
            case "SOUTH-UPPER-RIGHT-true-true" -> id+9;
            case "SOUTH-UPPER-RIGHT-true-false" -> id+10;
            case "SOUTH-UPPER-RIGHT-false-true" -> id+11;
            case "SOUTH-UPPER-RIGHT-false-false" -> id+12;
            case "SOUTH-LOWER-LEFT-true-true" -> id+13;
            case "SOUTH-LOWER-LEFT-true-false" -> id+14;
            case "SOUTH-LOWER-LEFT-false-true" -> id+15;
            case "SOUTH-LOWER-LEFT-false-false" -> id+16;
            case "SOUTH-LOWER-RIGHT-true-true" -> id+17;
            case "SOUTH-LOWER-RIGHT-true-false" -> id+18;
            case "SOUTH-LOWER-RIGHT-false-true" -> id+19;
            case "SOUTH-LOWER-RIGHT-false-false" -> id+20;
            case "WEST-UPPER-LEFT-true-true" -> id+21;
            case "WEST-UPPER-LEFT-true-false" -> id+22;
            case "WEST-UPPER-LEFT-false-true" -> id+23;
            case "WEST-UPPER-LEFT-false-false" -> id+24;
            case "WEST-UPPER-RIGHT-true-true" -> id+25;
            case "WEST-UPPER-RIGHT-true-false" -> id+26;
            case "WEST-UPPER-RIGHT-false-true" -> id+27;
            case "WEST-UPPER-RIGHT-false-false" -> id+28;
            case "WEST-LOWER-LEFT-true-true" -> id+29;
            case "WEST-LOWER-LEFT-true-false" -> id+30;
            case "WEST-LOWER-LEFT-false-true" -> id+31;
            case "WEST-LOWER-LEFT-false-false" -> id+32;
            case "WEST-LOWER-RIGHT-true-true" -> id+33;
            case "WEST-LOWER-RIGHT-true-false" -> id+34;
            case "WEST-LOWER-RIGHT-false-true" -> id+35;
            case "WEST-LOWER-RIGHT-false-false" -> id+36;
            case "EAST-UPPER-LEFT-true-true" -> id+37;
            case "EAST-UPPER-LEFT-true-false" -> id+38;
            case "EAST-UPPER-LEFT-false-true" -> id+39;
            case "EAST-UPPER-LEFT-false-false" -> id+40;
            case "EAST-UPPER-RIGHT-true-true" -> id+41;
            case "EAST-UPPER-RIGHT-true-false" -> id+42;
            case "EAST-UPPER-RIGHT-false-true" -> id+43;
            case "EAST-UPPER-RIGHT-false-false" -> id+44;
            case "EAST-LOWER-LEFT-true-true" -> id+45;
            case "EAST-LOWER-LEFT-true-false" -> id+46;
            case "EAST-LOWER-LEFT-false-true" -> id+47;
            case "EAST-LOWER-LEFT-false-false" -> id+48;
            case "EAST-LOWER-RIGHT-true-true" -> id+49;
            case "EAST-LOWER-RIGHT-true-false" -> id+50;
            case "EAST-LOWER-RIGHT-false-true" -> id+51;
            case "EAST-LOWER-RIGHT-false-false" -> id+52;
            default -> id;
        };
    }
}