/*
* Autogenerated file. Please don't touch :)
* Class generator: dev.hypix.dataparser.registry.wolf.WolfVariantParser (module data-parser)
* Date: Year: 2025. Month: 01. Day: 14. Time: 16:17:44
*/
package ink.reactor.entity.data.wolf;

import lombok.Getter;

import java.util.ArrayList;
import java.util.Collection;

@Getter
public final class WolfType {

    public static final Collection<WolfType> ALL = new ArrayList<>(9);

    private final String name;
    private final String angryTexture, tameTexture, wildTexture;

    public WolfType(String name, String angryTexture, String tameTexture, String wildTexture) {
        this.name = name;
        this.angryTexture = angryTexture;
        this.tameTexture = tameTexture;
        this.wildTexture = wildTexture;
    }

    private static WolfType vanilla(String name, String angryTexture, String tameTexture, String wildTexture) {
        final WolfType wolfType = new WolfType(name, angryTexture, tameTexture, wildTexture);
        ALL.add(wolfType);
        return wolfType;
    }

    public static final WolfType 
        STRIPED = vanilla("striped","minecraft:entity/wolf/wolf_striped_angry","minecraft:entity/wolf/wolf_striped_tame","minecraft:entity/wolf/wolf_striped"),
        ASHEN = vanilla("ashen","minecraft:entity/wolf/wolf_ashen_angry","minecraft:entity/wolf/wolf_ashen_tame","minecraft:entity/wolf/wolf_ashen"),
        WOODS = vanilla("woods","minecraft:entity/wolf/wolf_woods_angry","minecraft:entity/wolf/wolf_woods_tame","minecraft:entity/wolf/wolf_woods"),
        RUSTY = vanilla("rusty","minecraft:entity/wolf/wolf_rusty_angry","minecraft:entity/wolf/wolf_rusty_tame","minecraft:entity/wolf/wolf_rusty"),
        BLACK = vanilla("black","minecraft:entity/wolf/wolf_black_angry","minecraft:entity/wolf/wolf_black_tame","minecraft:entity/wolf/wolf_black"),
        CHESTNUT = vanilla("chestnut","minecraft:entity/wolf/wolf_chestnut_angry","minecraft:entity/wolf/wolf_chestnut_tame","minecraft:entity/wolf/wolf_chestnut"),
        PALE = vanilla("pale","minecraft:entity/wolf/wolf_angry","minecraft:entity/wolf/wolf_tame","minecraft:entity/wolf/wolf"),
        SNOWY = vanilla("snowy","minecraft:entity/wolf/wolf_snowy_angry","minecraft:entity/wolf/wolf_snowy_tame","minecraft:entity/wolf/wolf_snowy"),
        SPOTTED = vanilla("spotted","minecraft:entity/wolf/wolf_spotted_angry","minecraft:entity/wolf/wolf_spotted_tame","minecraft:entity/wolf/wolf_spotted");
}