/**
 * Autogenerated file. Please don't touch if you don't know :)
 * Class generator: ink.reactor.dataparser.type.wolf.WolfDataParser (module data-parser)
 * Date: Year: 2025. Month: 03. Day: 31. Hour: 01:15:21 (24h format)
 * <p>
 * Jsons combined using
 *   @see ink.reactor.dataparser.util.JsonCombiner
 * .json files generated with Data generators.
 *   <a href="https://minecraft.wiki/w/Minecraft_Wiki:Projects/wiki.vg_merge/Data_Generators">Data generators</a>
 */
package ink.reactor.entity.type.wolf;

import java.util.List;
import java.util.ArrayList;

public record WolfVariant(
    String name,
    String angryTexture,
    String biomes,
    String tameTexture,
    String wildTexture
) {
    public static final List<WolfVariant> ALL = new ArrayList<>(9);
    public static final WolfVariant ASHEN = vanilla("ashen","minecraft:entity/wolf/wolf_ashen_angry","minecraft:snowy_taiga","minecraft:entity/wolf/wolf_ashen_tame","minecraft:entity/wolf/wolf_ashen");
    public static final WolfVariant BLACK = vanilla("black","minecraft:entity/wolf/wolf_black_angry","minecraft:old_growth_pine_taiga","minecraft:entity/wolf/wolf_black_tame","minecraft:entity/wolf/wolf_black");
    public static final WolfVariant CHESTNUT = vanilla("chestnut","minecraft:entity/wolf/wolf_chestnut_angry","minecraft:old_growth_spruce_taiga","minecraft:entity/wolf/wolf_chestnut_tame","minecraft:entity/wolf/wolf_chestnut");
    public static final WolfVariant PALE = vanilla("pale","minecraft:entity/wolf/wolf_angry","minecraft:taiga","minecraft:entity/wolf/wolf_tame","minecraft:entity/wolf/wolf");
    public static final WolfVariant RUSTY = vanilla("rusty","minecraft:entity/wolf/wolf_rusty_angry","#minecraft:is_jungle","minecraft:entity/wolf/wolf_rusty_tame","minecraft:entity/wolf/wolf_rusty");
    public static final WolfVariant SNOWY = vanilla("snowy","minecraft:entity/wolf/wolf_snowy_angry","minecraft:grove","minecraft:entity/wolf/wolf_snowy_tame","minecraft:entity/wolf/wolf_snowy");
    public static final WolfVariant SPOTTED = vanilla("spotted","minecraft:entity/wolf/wolf_spotted_angry","#minecraft:is_savanna","minecraft:entity/wolf/wolf_spotted_tame","minecraft:entity/wolf/wolf_spotted");
    public static final WolfVariant STRIPED = vanilla("striped","minecraft:entity/wolf/wolf_striped_angry","#minecraft:is_badlands","minecraft:entity/wolf/wolf_striped_tame","minecraft:entity/wolf/wolf_striped");
    public static final WolfVariant WOODS = vanilla("woods","minecraft:entity/wolf/wolf_woods_angry","minecraft:forest","minecraft:entity/wolf/wolf_woods_tame","minecraft:entity/wolf/wolf_woods");
    private static WolfVariant vanilla(String name, String angryTexture, String biomes, String tameTexture, String wildTexture) {
        final WolfVariant instance = new WolfVariant(name, angryTexture, biomes, tameTexture, wildTexture);
        ALL.add(instance);
        return instance;
    }
}