/**
 * Autogenerated file. Please don't touch if you don't know :)
 * Class generator: ink.reactor.dataparser.type.trim.TrimPatternDataParser (module data-parser)
 * Date: Year: 2025. Month: 03. Day: 31. Hour: 00:54:39 (24h format)
 * <p>
 * Jsons combined using
 *   @see ink.reactor.dataparser.util.JsonCombiner
 * .json files generated with Data generators.
 *   <a href="https://minecraft.wiki/w/Minecraft_Wiki:Projects/wiki.vg_merge/Data_Generators">Data generators</a>
 */
package ink.reactor.item.data.armor;

import java.util.List;
import java.util.ArrayList;

public record TrimPattern(
    String assetId,
    String description,
    String templateItem,
    boolean decal
) {
    public static final List<TrimPattern> ALL = new ArrayList<>(18);
    public static final TrimPattern BOLT = vanilla("minecraft:bolt","trim_pattern.minecraft.bolt","minecraft:bolt_armor_trim_smithing_template",false);
    public static final TrimPattern COAST = vanilla("minecraft:coast","trim_pattern.minecraft.coast","minecraft:coast_armor_trim_smithing_template",false);
    public static final TrimPattern DUNE = vanilla("minecraft:dune","trim_pattern.minecraft.dune","minecraft:dune_armor_trim_smithing_template",false);
    public static final TrimPattern EYE = vanilla("minecraft:eye","trim_pattern.minecraft.eye","minecraft:eye_armor_trim_smithing_template",false);
    public static final TrimPattern FLOW = vanilla("minecraft:flow","trim_pattern.minecraft.flow","minecraft:flow_armor_trim_smithing_template",false);
    public static final TrimPattern HOST = vanilla("minecraft:host","trim_pattern.minecraft.host","minecraft:host_armor_trim_smithing_template",false);
    public static final TrimPattern RAISER = vanilla("minecraft:raiser","trim_pattern.minecraft.raiser","minecraft:raiser_armor_trim_smithing_template",false);
    public static final TrimPattern RIB = vanilla("minecraft:rib","trim_pattern.minecraft.rib","minecraft:rib_armor_trim_smithing_template",false);
    public static final TrimPattern SENTRY = vanilla("minecraft:sentry","trim_pattern.minecraft.sentry","minecraft:sentry_armor_trim_smithing_template",false);
    public static final TrimPattern SHAPER = vanilla("minecraft:shaper","trim_pattern.minecraft.shaper","minecraft:shaper_armor_trim_smithing_template",false);
    public static final TrimPattern SILENCE = vanilla("minecraft:silence","trim_pattern.minecraft.silence","minecraft:silence_armor_trim_smithing_template",false);
    public static final TrimPattern SNOUT = vanilla("minecraft:snout","trim_pattern.minecraft.snout","minecraft:snout_armor_trim_smithing_template",false);
    public static final TrimPattern SPIRE = vanilla("minecraft:spire","trim_pattern.minecraft.spire","minecraft:spire_armor_trim_smithing_template",false);
    public static final TrimPattern TIDE = vanilla("minecraft:tide","trim_pattern.minecraft.tide","minecraft:tide_armor_trim_smithing_template",false);
    public static final TrimPattern VEX = vanilla("minecraft:vex","trim_pattern.minecraft.vex","minecraft:vex_armor_trim_smithing_template",false);
    public static final TrimPattern WARD = vanilla("minecraft:ward","trim_pattern.minecraft.ward","minecraft:ward_armor_trim_smithing_template",false);
    public static final TrimPattern WAYFINDER = vanilla("minecraft:wayfinder","trim_pattern.minecraft.wayfinder","minecraft:wayfinder_armor_trim_smithing_template",false);
    public static final TrimPattern WILD = vanilla("minecraft:wild","trim_pattern.minecraft.wild","minecraft:wild_armor_trim_smithing_template",false);
    private static TrimPattern vanilla(String assetId, String description, String templateItem, boolean decal) {
        final TrimPattern instance = new TrimPattern(assetId, description, templateItem, decal);
        ALL.add(instance);
        return instance;
    }
}