/**
* Autogenerated file. Please don't touch if you don't know :)
* Class generator: ink.reactor.dataparser.type.banner.BannerDataParser (module data-parser)
* Date: Year: 2025. Month: 03. Day: 31. Hour: 00:54:39 (24h format)
* <p>
* Jsons combined using 
*   @see ink.reactor.dataparser.util.JsonCombiner
* .json files generated with Data generators. 
*   <a href="https://minecraft.wiki/w/Minecraft_Wiki:Projects/wiki.vg_merge/Data_Generators">Data generators</a>
*/
package ink.reactor.world.block;

import java.util.List;
import java.util.ArrayList;

public final record BannerPattern(
    String assetId,
    String translationKey
) {
    public static final List<BannerPattern> ALL = new ArrayList<>(43);
    public static final BannerPattern BASE = vanilla("minecraft:base","block.minecraft.banner.base");
    public static final BannerPattern BORDER = vanilla("minecraft:border","block.minecraft.banner.border");
    public static final BannerPattern BRICKS = vanilla("minecraft:bricks","block.minecraft.banner.bricks");
    public static final BannerPattern CIRCLE = vanilla("minecraft:circle","block.minecraft.banner.circle");
    public static final BannerPattern CREEPER = vanilla("minecraft:creeper","block.minecraft.banner.creeper");
    public static final BannerPattern CROSS = vanilla("minecraft:cross","block.minecraft.banner.cross");
    public static final BannerPattern CURLY_BORDER = vanilla("minecraft:curly_border","block.minecraft.banner.curly_border");
    public static final BannerPattern DIAGONAL_LEFT = vanilla("minecraft:diagonal_left","block.minecraft.banner.diagonal_left");
    public static final BannerPattern DIAGONAL_RIGHT = vanilla("minecraft:diagonal_right","block.minecraft.banner.diagonal_right");
    public static final BannerPattern DIAGONAL_UP_LEFT = vanilla("minecraft:diagonal_up_left","block.minecraft.banner.diagonal_up_left");
    public static final BannerPattern DIAGONAL_UP_RIGHT = vanilla("minecraft:diagonal_up_right","block.minecraft.banner.diagonal_up_right");
    public static final BannerPattern FLOW = vanilla("minecraft:flow","block.minecraft.banner.flow");
    public static final BannerPattern FLOWER = vanilla("minecraft:flower","block.minecraft.banner.flower");
    public static final BannerPattern GLOBE = vanilla("minecraft:globe","block.minecraft.banner.globe");
    public static final BannerPattern GRADIENT = vanilla("minecraft:gradient","block.minecraft.banner.gradient");
    public static final BannerPattern GRADIENT_UP = vanilla("minecraft:gradient_up","block.minecraft.banner.gradient_up");
    public static final BannerPattern GUSTER = vanilla("minecraft:guster","block.minecraft.banner.guster");
    public static final BannerPattern HALF_HORIZONTAL = vanilla("minecraft:half_horizontal","block.minecraft.banner.half_horizontal");
    public static final BannerPattern HALF_HORIZONTAL_BOTTOM = vanilla("minecraft:half_horizontal_bottom","block.minecraft.banner.half_horizontal_bottom");
    public static final BannerPattern HALF_VERTICAL = vanilla("minecraft:half_vertical","block.minecraft.banner.half_vertical");
    public static final BannerPattern HALF_VERTICAL_RIGHT = vanilla("minecraft:half_vertical_right","block.minecraft.banner.half_vertical_right");
    public static final BannerPattern MOJANG = vanilla("minecraft:mojang","block.minecraft.banner.mojang");
    public static final BannerPattern PIGLIN = vanilla("minecraft:piglin","block.minecraft.banner.piglin");
    public static final BannerPattern RHOMBUS = vanilla("minecraft:rhombus","block.minecraft.banner.rhombus");
    public static final BannerPattern SKULL = vanilla("minecraft:skull","block.minecraft.banner.skull");
    public static final BannerPattern SMALL_STRIPES = vanilla("minecraft:small_stripes","block.minecraft.banner.small_stripes");
    public static final BannerPattern SQUARE_BOTTOM_LEFT = vanilla("minecraft:square_bottom_left","block.minecraft.banner.square_bottom_left");
    public static final BannerPattern SQUARE_BOTTOM_RIGHT = vanilla("minecraft:square_bottom_right","block.minecraft.banner.square_bottom_right");
    public static final BannerPattern SQUARE_TOP_LEFT = vanilla("minecraft:square_top_left","block.minecraft.banner.square_top_left");
    public static final BannerPattern SQUARE_TOP_RIGHT = vanilla("minecraft:square_top_right","block.minecraft.banner.square_top_right");
    public static final BannerPattern STRAIGHT_CROSS = vanilla("minecraft:straight_cross","block.minecraft.banner.straight_cross");
    public static final BannerPattern STRIPE_BOTTOM = vanilla("minecraft:stripe_bottom","block.minecraft.banner.stripe_bottom");
    public static final BannerPattern STRIPE_CENTER = vanilla("minecraft:stripe_center","block.minecraft.banner.stripe_center");
    public static final BannerPattern STRIPE_DOWNLEFT = vanilla("minecraft:stripe_downleft","block.minecraft.banner.stripe_downleft");
    public static final BannerPattern STRIPE_DOWNRIGHT = vanilla("minecraft:stripe_downright","block.minecraft.banner.stripe_downright");
    public static final BannerPattern STRIPE_LEFT = vanilla("minecraft:stripe_left","block.minecraft.banner.stripe_left");
    public static final BannerPattern STRIPE_MIDDLE = vanilla("minecraft:stripe_middle","block.minecraft.banner.stripe_middle");
    public static final BannerPattern STRIPE_RIGHT = vanilla("minecraft:stripe_right","block.minecraft.banner.stripe_right");
    public static final BannerPattern STRIPE_TOP = vanilla("minecraft:stripe_top","block.minecraft.banner.stripe_top");
    public static final BannerPattern TRIANGLE_BOTTOM = vanilla("minecraft:triangle_bottom","block.minecraft.banner.triangle_bottom");
    public static final BannerPattern TRIANGLE_TOP = vanilla("minecraft:triangle_top","block.minecraft.banner.triangle_top");
    public static final BannerPattern TRIANGLES_BOTTOM = vanilla("minecraft:triangles_bottom","block.minecraft.banner.triangles_bottom");
    public static final BannerPattern TRIANGLES_TOP = vanilla("minecraft:triangles_top","block.minecraft.banner.triangles_top");
    private static BannerPattern vanilla(String assetId, String translationKey) {
        final BannerPattern instance = new BannerPattern(assetId, translationKey);
        ALL.add(instance);
        return instance;
    }
}