/**
* Autogenerated file. Please don't touch if you don't know :)
* Class generator: ink.reactor.dataparser.type.sound.JukeboxDataParser (module data-parser)
* Date: Year: 2025. Month: 03. Day: 31. Hour: 00:54:39 (24h format)
* <p>
* Jsons combined using 
*   @see ink.reactor.dataparser.util.JsonCombiner
* .json files generated with Data generators. 
*   <a href="https://minecraft.wiki/w/Minecraft_Wiki:Projects/wiki.vg_merge/Data_Generators">Data generators</a>
*/
package ink.reactor.world.block;

import java.util.List;
import java.util.ArrayList;

public final record Jukebox(
    String description,
    String soundEvent,
    int comparatorOutput,
    double lengthInSeconds
) {
    public static final List<Jukebox> ALL = new ArrayList<>(19);
    public static final Jukebox NUMBER_11 = vanilla("jukebox_song.minecraft.11","minecraft:music_disc.11",11,71.0);
    public static final Jukebox NUMBER_13 = vanilla("jukebox_song.minecraft.13","minecraft:music_disc.13",1,178.0);
    public static final Jukebox NUMBER_5 = vanilla("jukebox_song.minecraft.5","minecraft:music_disc.5",15,178.0);
    public static final Jukebox BLOCKS = vanilla("jukebox_song.minecraft.blocks","minecraft:music_disc.blocks",3,345.0);
    public static final Jukebox CAT = vanilla("jukebox_song.minecraft.cat","minecraft:music_disc.cat",2,185.0);
    public static final Jukebox CHIRP = vanilla("jukebox_song.minecraft.chirp","minecraft:music_disc.chirp",4,185.0);
    public static final Jukebox CREATOR = vanilla("jukebox_song.minecraft.creator","minecraft:music_disc.creator",12,176.0);
    public static final Jukebox CREATOR_MUSIC_BOX = vanilla("jukebox_song.minecraft.creator_music_box","minecraft:music_disc.creator_music_box",11,73.0);
    public static final Jukebox FAR = vanilla("jukebox_song.minecraft.far","minecraft:music_disc.far",5,174.0);
    public static final Jukebox MALL = vanilla("jukebox_song.minecraft.mall","minecraft:music_disc.mall",6,197.0);
    public static final Jukebox MELLOHI = vanilla("jukebox_song.minecraft.mellohi","minecraft:music_disc.mellohi",7,96.0);
    public static final Jukebox OTHERSIDE = vanilla("jukebox_song.minecraft.otherside","minecraft:music_disc.otherside",14,195.0);
    public static final Jukebox PIGSTEP = vanilla("jukebox_song.minecraft.pigstep","minecraft:music_disc.pigstep",13,149.0);
    public static final Jukebox PRECIPICE = vanilla("jukebox_song.minecraft.precipice","minecraft:music_disc.precipice",13,299.0);
    public static final Jukebox RELIC = vanilla("jukebox_song.minecraft.relic","minecraft:music_disc.relic",14,218.0);
    public static final Jukebox STAL = vanilla("jukebox_song.minecraft.stal","minecraft:music_disc.stal",8,150.0);
    public static final Jukebox STRAD = vanilla("jukebox_song.minecraft.strad","minecraft:music_disc.strad",9,188.0);
    public static final Jukebox WAIT = vanilla("jukebox_song.minecraft.wait","minecraft:music_disc.wait",12,238.0);
    public static final Jukebox WARD = vanilla("jukebox_song.minecraft.ward","minecraft:music_disc.ward",10,251.0);
    private static Jukebox vanilla(String description, String soundEvent, int comparatorOutput, double lengthInSeconds) {
        final Jukebox instance = new Jukebox(description, soundEvent, comparatorOutput, lengthInSeconds);
        ALL.add(instance);
        return instance;
    }
}