/**
* Autogenerated file. Please don't touch if you don't know :)
* Class generator: ink.reactor.dataparser.type.painting.PaintingDataParser (module data-parser)
* Date: Year: 2025. Month: 03. Day: 31. Hour: 00:54:40 (24h format)
* <p>
* Jsons combined using 
*   @see ink.reactor.dataparser.util.JsonCombiner
* .json files generated with Data generators. 
*   <a href="https://minecraft.wiki/w/Minecraft_Wiki:Projects/wiki.vg_merge/Data_Generators">Data generators</a>
*/
package ink.reactor.world.block;

import java.util.List;
import java.util.ArrayList;

public final record PaintingVariant(
    String assetId,
    String author,
    String title,
    byte height,
    byte width
) {
    public static final List<PaintingVariant> ALL = new ArrayList<>(50);
    public static final PaintingVariant ALBAN = vanilla("minecraft:alban","painting.minecraft.alban.author","painting.minecraft.alban.title",1,1);
    public static final PaintingVariant AZTEC = vanilla("minecraft:aztec","painting.minecraft.aztec.author","painting.minecraft.aztec.title",1,1);
    public static final PaintingVariant AZTEC2 = vanilla("minecraft:aztec2","painting.minecraft.aztec2.author","painting.minecraft.aztec2.title",1,1);
    public static final PaintingVariant BACKYARD = vanilla("minecraft:backyard","painting.minecraft.backyard.author","painting.minecraft.backyard.title",4,3);
    public static final PaintingVariant BAROQUE = vanilla("minecraft:baroque","painting.minecraft.baroque.author","painting.minecraft.baroque.title",2,2);
    public static final PaintingVariant BOMB = vanilla("minecraft:bomb","painting.minecraft.bomb.author","painting.minecraft.bomb.title",1,1);
    public static final PaintingVariant BOUQUET = vanilla("minecraft:bouquet","painting.minecraft.bouquet.author","painting.minecraft.bouquet.title",3,3);
    public static final PaintingVariant BURNING_SKULL = vanilla("minecraft:burning_skull","painting.minecraft.burning_skull.author","painting.minecraft.burning_skull.title",4,4);
    public static final PaintingVariant BUST = vanilla("minecraft:bust","painting.minecraft.bust.author","painting.minecraft.bust.title",2,2);
    public static final PaintingVariant CAVEBIRD = vanilla("minecraft:cavebird","painting.minecraft.cavebird.author","painting.minecraft.cavebird.title",3,3);
    public static final PaintingVariant CHANGING = vanilla("minecraft:changing","painting.minecraft.changing.author","painting.minecraft.changing.title",2,4);
    public static final PaintingVariant COTAN = vanilla("minecraft:cotan","painting.minecraft.cotan.author","painting.minecraft.cotan.title",3,3);
    public static final PaintingVariant COURBET = vanilla("minecraft:courbet","painting.minecraft.courbet.author","painting.minecraft.courbet.title",1,2);
    public static final PaintingVariant CREEBET = vanilla("minecraft:creebet","painting.minecraft.creebet.author","painting.minecraft.creebet.title",1,2);
    public static final PaintingVariant DONKEY_KONG = vanilla("minecraft:donkey_kong","painting.minecraft.donkey_kong.author","painting.minecraft.donkey_kong.title",3,4);
    public static final PaintingVariant EARTH = vanilla("minecraft:earth","","painting.minecraft.earth.title",2,2);
    public static final PaintingVariant ENDBOSS = vanilla("minecraft:endboss","painting.minecraft.endboss.author","painting.minecraft.endboss.title",3,3);
    public static final PaintingVariant FERN = vanilla("minecraft:fern","painting.minecraft.fern.author","painting.minecraft.fern.title",3,3);
    public static final PaintingVariant FIGHTERS = vanilla("minecraft:fighters","painting.minecraft.fighters.author","painting.minecraft.fighters.title",2,4);
    public static final PaintingVariant FINDING = vanilla("minecraft:finding","painting.minecraft.finding.author","painting.minecraft.finding.title",2,4);
    public static final PaintingVariant FIRE = vanilla("minecraft:fire","","painting.minecraft.fire.title",2,2);
    public static final PaintingVariant GRAHAM = vanilla("minecraft:graham","painting.minecraft.graham.author","painting.minecraft.graham.title",2,1);
    public static final PaintingVariant HUMBLE = vanilla("minecraft:humble","painting.minecraft.humble.author","painting.minecraft.humble.title",2,2);
    public static final PaintingVariant KEBAB = vanilla("minecraft:kebab","painting.minecraft.kebab.author","painting.minecraft.kebab.title",1,1);
    public static final PaintingVariant LOWMIST = vanilla("minecraft:lowmist","painting.minecraft.lowmist.author","painting.minecraft.lowmist.title",2,4);
    public static final PaintingVariant MATCH = vanilla("minecraft:match","painting.minecraft.match.author","painting.minecraft.match.title",2,2);
    public static final PaintingVariant MEDITATIVE = vanilla("minecraft:meditative","painting.minecraft.meditative.author","painting.minecraft.meditative.title",1,1);
    public static final PaintingVariant ORB = vanilla("minecraft:orb","painting.minecraft.orb.author","painting.minecraft.orb.title",4,4);
    public static final PaintingVariant OWLEMONS = vanilla("minecraft:owlemons","painting.minecraft.owlemons.author","painting.minecraft.owlemons.title",3,3);
    public static final PaintingVariant PASSAGE = vanilla("minecraft:passage","painting.minecraft.passage.author","painting.minecraft.passage.title",2,4);
    public static final PaintingVariant PIGSCENE = vanilla("minecraft:pigscene","painting.minecraft.pigscene.author","painting.minecraft.pigscene.title",4,4);
    public static final PaintingVariant PLANT = vanilla("minecraft:plant","painting.minecraft.plant.author","painting.minecraft.plant.title",1,1);
    public static final PaintingVariant POINTER = vanilla("minecraft:pointer","painting.minecraft.pointer.author","painting.minecraft.pointer.title",4,4);
    public static final PaintingVariant POND = vanilla("minecraft:pond","painting.minecraft.pond.author","painting.minecraft.pond.title",4,3);
    public static final PaintingVariant POOL = vanilla("minecraft:pool","painting.minecraft.pool.author","painting.minecraft.pool.title",1,2);
    public static final PaintingVariant PRAIRIE_RIDE = vanilla("minecraft:prairie_ride","painting.minecraft.prairie_ride.author","painting.minecraft.prairie_ride.title",2,1);
    public static final PaintingVariant SEA = vanilla("minecraft:sea","painting.minecraft.sea.author","painting.minecraft.sea.title",1,2);
    public static final PaintingVariant SKELETON = vanilla("minecraft:skeleton","painting.minecraft.skeleton.author","painting.minecraft.skeleton.title",3,4);
    public static final PaintingVariant SKULL_AND_ROSES = vanilla("minecraft:skull_and_roses","painting.minecraft.skull_and_roses.author","painting.minecraft.skull_and_roses.title",2,2);
    public static final PaintingVariant STAGE = vanilla("minecraft:stage","painting.minecraft.stage.author","painting.minecraft.stage.title",2,2);
    public static final PaintingVariant SUNFLOWERS = vanilla("minecraft:sunflowers","painting.minecraft.sunflowers.author","painting.minecraft.sunflowers.title",3,3);
    public static final PaintingVariant SUNSET = vanilla("minecraft:sunset","painting.minecraft.sunset.author","painting.minecraft.sunset.title",1,2);
    public static final PaintingVariant TIDES = vanilla("minecraft:tides","painting.minecraft.tides.author","painting.minecraft.tides.title",3,3);
    public static final PaintingVariant UNPACKED = vanilla("minecraft:unpacked","painting.minecraft.unpacked.author","painting.minecraft.unpacked.title",4,4);
    public static final PaintingVariant VOID = vanilla("minecraft:void","painting.minecraft.void.author","painting.minecraft.void.title",2,2);
    public static final PaintingVariant WANDERER = vanilla("minecraft:wanderer","painting.minecraft.wanderer.author","painting.minecraft.wanderer.title",2,1);
    public static final PaintingVariant WASTELAND = vanilla("minecraft:wasteland","painting.minecraft.wasteland.author","painting.minecraft.wasteland.title",1,1);
    public static final PaintingVariant WATER = vanilla("minecraft:water","","painting.minecraft.water.title",2,2);
    public static final PaintingVariant WIND = vanilla("minecraft:wind","","painting.minecraft.wind.title",2,2);
    public static final PaintingVariant WITHER = vanilla("minecraft:wither","","painting.minecraft.wither.title",2,2);
    private static PaintingVariant vanilla(String assetId, String author, String title, int height, int width) {
        final PaintingVariant instance = new PaintingVariant(assetId, author, title, (byte)height, (byte)width);
        ALL.add(instance);
        return instance;
    }
}